name: Update Submodules

on:
  repository_dispatch:
    types: [update-submodules-event]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the main repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures all history is fetched including tags

    - name: Update submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive --remote --merge

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Automatically updated submodules" || echo "No changes to commit"
        git remote set-url origin https://${{ secrets.GITMANAGE_PAT }}@github.com/karniib/gitManage.git
        git push || echo "Failed to push"
