# This is a basic workflow to help you get started with Actions

name: Update Submodules

on:
  schedule:

    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fullstack
      uses: actions/checkout@v2
      with:
        submodules: true 

    - name: synchronize changes from submodules to main repo
      run: |
        git submodule update --init --recursive
        git submodule foreach 'git fetch origin main && git reset --hard origin/main'
        git add .
        git commit -m "synchronize changes" || echo "No changes to commit"
        git push origin main
